/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretVerifyVapidRouteImport } from './routes/secret/verify-vapid'
import { Route as SecretTestNotifyRouteImport } from './routes/secret/test-notify'
import { Route as SecretFeedRouteImport } from './routes/secret/feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretVerifyVapidRoute = SecretVerifyVapidRouteImport.update({
  id: '/secret/verify-vapid',
  path: '/secret/verify-vapid',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretTestNotifyRoute = SecretTestNotifyRouteImport.update({
  id: '/secret/test-notify',
  path: '/secret/test-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretFeedRoute = SecretFeedRouteImport.update({
  id: '/secret/feed',
  path: '/secret/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secret/feed': typeof SecretFeedRoute
  '/secret/test-notify': typeof SecretTestNotifyRoute
  '/secret/verify-vapid': typeof SecretVerifyVapidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/secret/feed': typeof SecretFeedRoute
  '/secret/test-notify': typeof SecretTestNotifyRoute
  '/secret/verify-vapid': typeof SecretVerifyVapidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secret/feed': typeof SecretFeedRoute
  '/secret/test-notify': typeof SecretTestNotifyRoute
  '/secret/verify-vapid': typeof SecretVerifyVapidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/secret/feed'
    | '/secret/test-notify'
    | '/secret/verify-vapid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/secret/feed' | '/secret/test-notify' | '/secret/verify-vapid'
  id:
    | '__root__'
    | '/'
    | '/secret/feed'
    | '/secret/test-notify'
    | '/secret/verify-vapid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecretFeedRoute: typeof SecretFeedRoute
  SecretTestNotifyRoute: typeof SecretTestNotifyRoute
  SecretVerifyVapidRoute: typeof SecretVerifyVapidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/verify-vapid': {
      id: '/secret/verify-vapid'
      path: '/secret/verify-vapid'
      fullPath: '/secret/verify-vapid'
      preLoaderRoute: typeof SecretVerifyVapidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/test-notify': {
      id: '/secret/test-notify'
      path: '/secret/test-notify'
      fullPath: '/secret/test-notify'
      preLoaderRoute: typeof SecretTestNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/feed': {
      id: '/secret/feed'
      path: '/secret/feed'
      fullPath: '/secret/feed'
      preLoaderRoute: typeof SecretFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecretFeedRoute: SecretFeedRoute,
  SecretTestNotifyRoute: SecretTestNotifyRoute,
  SecretVerifyVapidRoute: SecretVerifyVapidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
